---
services:

  readeef:
    image: readeef:alpine3.10-go1.13
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    command: ["readeef", "server"]

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data: