---
version: "3.7"
services:

  zero:
    image: dgraph/dgraph:latest
    volumes:
    - ./data0/data-volume:/dgraph
    ports:
    - 5080:5080
    - 6080:6080
    command: dgraph zero --my=zero:5080 --replicas 3

  server_1:
    image: dgraph/dgraph:latest
    hostname: "server_1"
    volumes:
    - ./data1/data-volume:/dgraph
    ports:
    - 8080:8080
    - 9080:9080
    command: dgraph server --my=server_1:7080 --lru_mb=4096 --zero=zero:5080

  server_2:
    image: dgraph/dgraph:latest
    hostname: "server_2"
    volumes:
    - ./data2/data-volume:/dgraph
    ports:
    - 8081:8081
    - 9081:9081
    command: dgraph server --my=server_2:7081 --lru_mb=4096 --zero=zero:5080 -o 1

  server_3:
    image: dgraph/dgraph:latest
    hostname: "server_3"
    volumes:
    - ./data3/data-volume:/dgraph
    ports:
    - 8082:8082
    - 9082:9082
    command: dgraph server --my=server_3:7082 --lru_mb=4096 --zero=zero:5080 -o 2

  ratel:
    image: dgraph/dgraph:latest
    hostname: "ratel"
    ports:
    - 8000:8000
    command: dgraph-ratel
