// Code generated by "stringer -type articleRepoType api"; DO NOT EDIT.

package api

import "fmt"

const _articleRepoType_name = "userRepoTypefavoriteRepoTypepopularRepoTypetagRepoTypefeedRepoType"

var _articleRepoType_index = [...]uint8{0, 12, 28, 43, 54, 66}

func (i articleRepoType) String() string {
	if i < 0 || i >= articleRepoType(len(_articleRepoType_index)-1) {
		return fmt.Sprintf("articleRepoType(%d)", i)
	}
	return _articleRepoType_name[_articleRepoType_index[i]:_articleRepoType_index[i+1]]
}
