// Code generated by "stringer -type articleState"; DO NOT EDIT.

package api

import "fmt"

const _articleState_name = "readfavorite"

var _articleState_index = [...]uint8{0, 4, 12}

func (i articleState) String() string {
	if i < 0 || i >= articleState(len(_articleState_index)-1) {
		return fmt.Sprintf("articleState(%d)", i)
	}
	return _articleState_name[_articleState_index[i]:_articleState_index[i+1]]
}
